### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by m-overlund** [HEPTACOM/HeptacomShopwarePlatformAdminOpenAuth#39]
### Plugin Version

6.0.4

### PHP Version

8.2.28

### Shopware Version

6.5.7.3

### Installation method

Composer

### Identity provider

Microsoft Azure OIDC

### What happened?

using Entra

After updating from 6.0.3 to 6.0.4
Plugin does not work.

Upon update it throws this error:

```
06:04:48 CRITICAL  [console] Error thrown while running command "plugin:update:all". Message: "Class "Heptacom\AdminOpenAuth\Database\Aggregate\ClientAclRoleDefinition" not found" ["exception" => Error { …},"command" => "plugin:update:all","message" => "Class "Heptacom\AdminOpenAuth\Database\Aggregate\ClientAclRoleDefinition" not found"]

In Shopware_Core_KernelProdContainer.php line 3193:

  Attempted to load class "ClientAclRoleDefinition" from namespace "Heptacom\AdminOpenAuth\Database\Aggregate".
  Did you forget a "use" statement for another namespace?
``` 

### Relevant log output

```shell

```

**Comment by silviokennecke** [comment]
I just checked with a clean Shopware installation and was able to perform the update without any issues. It seems to me that there might be some issue with your cache. Could you try a `bin/console cache:clear` before running `plugin:update:all` again?

**Comment by m-overlund** [comment]
## Old data
Issue was there was extension data in `custom/plugins` which i didn't know about. My bad.


## New issue - can't login
But it seems `keep user updated` hasn't been changed thoroughly.
Tested on multiple instances.

## Issues
1. In auth client settings, the `update user info` button is still there. But it does not work. It switches off / does not store data.
2. When logging in through module (i use Azure/Entra) i get the error below.

## Error on login
```json
{"errors":[{"status":"400","code":"FRAMEWORK__UNMAPPED_FIELD","title":"Bad Request","detail":"Field \u0022keepUserUpdated\u0022 in entity \u0022heptacom_admin_open_auth_client\u0022 was not found.","meta":{"parameters":{"field":"keepUserUpdated","entity":"heptacom_admin_open_auth_client"}}}]}
```

![Image](https://github.com/user-attachments/assets/143cfc1b-3a13-4263-89c8-3b89055cb8d3)

**Comment by silviokennecke** [comment]
Hi @m-overlund due to a bug (also causing your issue), we revoked 6.0.4 today. We just released 6.0.5 which fixes that.

**Comment by m-overlund** [comment]
hi @silviokennecke 
6.0.5 does fix the issue - thanks.

However the "My extensions" page i admin still have issues after updating to 6.0.5.
It simply still breaks and only shows 7 extensions on the first page - suspectedly because it breaks when it comes to this module.
(The other pages works fine)

How do we fix that?
